spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/dosan
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100


logging.level:
  org.hibernate.SQL: debug

file.dir: C:/work/source/spring-boot/dosan/imgUpload/
