spring:
  # H2 Database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dosan
    username: sa
    password:

  h2:
    console:
      enabled: true

  # JPA
  jpa:
    hibernate:
#      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  # Messages
  messages:
    basename: messages, errors

# Hibernate Batch Size
hibernate:
  default_batch_fetch_size: 100

# Log Level
logging.level:
  org.hibernate.SQL: info

# File Path
file:
  dir: C:/upload/file/
  temp: C:/upload/temp/
  signature: C:/upload/signature/
